// Offline preview check. Uses an installed Playwright package; no web server.
const { chromium } = require(process.env.PLAYWRIGHT_PATH || 'playwright');
const { pathToFileURL } = require('node:url');
const path = require('node:path');
const assert = require('node:assert/strict');
(async () => {
  const browser = await chromium.launch({channel:'msedge',headless:true});
  try {
    const page = await browser.newPage({viewport:{width:1440,height:1060}});
    const errors = [], requests = [];
    page.on('pageerror', e => errors.push(e.message));
    page.on('request', r => {if (/^https?:/.test(r.url())) requests.push(r.url());});
    await page.goto(pathToFileURL(path.join(__dirname,'tls-cluster-preview.html')).href);
    await page.screenshot({path:path.join(__dirname,'preview-tasks.png'),fullPage:true,animations:'disabled',style:' .toast{visibility:hidden} '});
    assert.equal(await page.locator('tbody tr').count(),5);
    await page.locator('[data-page="2"]').click();
    assert.equal(await page.locator('tbody tr').count(),1);
    await page.locator('[data-filter="error"]').click();
    await page.locator('[data-task="39"]').first().click();
    assert.match(await page.locator('.log').innerText(),/Попытка 3\/3/);
    await page.locator('#restartTask').click();
    assert.match(await page.locator('h1').innerText(),/#43/);
    assert.equal(await page.locator('#restartTask').isEnabled(),true);
    await page.locator('[data-action="tasks"]').click();
    await page.locator('[data-filter="all"]').click();
    await page.locator('#search').fill('01208sm6');
    assert.equal(await page.locator('tbody tr').count(),1);
    await page.locator('[data-task="42"]').first().click();
    assert.equal(await page.locator('#restartTask').isDisabled(),true);
    await page.screenshot({path:path.join(__dirname,'preview-detail.png'),fullPage:true,animations:'disabled',style:' .toast{visibility:hidden} '});
    await page.locator('[data-log="0"]').click();
    assert.match(await page.locator('.log').innerText(),/Обработка завершена/);
    await page.locator('#cancelTask').click();
    await page.locator('#confirmCancel').click();
    assert.equal(await page.locator('#cancelTask').isDisabled(),true);
    assert.equal(await page.locator('#restartTask').isEnabled(),true);
    assert.equal(await page.locator('tbody .status.processing').count(),0);
    await page.locator('[data-view="create"]').click();
    assert.match(await page.locator('#outputPath').inputValue(),/_classified$/);
    assert.equal(await page.locator('[data-browse="output"]').isDisabled(),true);
    await page.screenshot({path:path.join(__dirname,'preview-create.png'),fullPage:true,animations:'disabled',style:' .toast{visibility:hidden} '});
    await page.locator('#autoOutput').uncheck();
    await page.locator('[data-browse="output"]').click();
    await page.locator('#newFolder').click();
    await page.locator('#folderName').fill('Review 2026');
    await page.locator('#saveFolder').click();
    await page.locator('[data-folder$="/Review 2026"]').click();
    await page.locator('#pickFolder').click();
    assert.match(await page.locator('#outputPath').inputValue(),/Review 2026$/);
    await page.locator('#inputPath').fill('/172.16.16.126/ishod/../bad');
    await page.locator('button[type="submit"]').click();
    assert.match(await page.locator('#formError').innerText(),/Выберите разные/);
    await page.locator('#inputPath').fill('/172.16.16.126/ishod/new_scene');
    await page.locator('#autoOutput').check();
    await page.locator('button[type="submit"]').click();
    assert.match(await page.locator('h1').innerText(),/#44/);
    assert.match(await page.locator('.pathpair').innerText(),/new_scene_classified/);
    await page.setViewportSize({width:390,height:844});
    await page.locator('[data-view="create"]').click();
    await page.screenshot({path:path.join(__dirname,'preview-mobile.png'),fullPage:true,animations:'disabled',style:' .toast{visibility:hidden} '});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
    await page.locator('[data-browse="input"]').click();
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('#folderDialog').evaluate(d=>d.open),false);
    await page.locator('[data-view="tasks"]').click();
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
    assert.deepEqual(errors,[]);
    assert.deepEqual(requests,[]);
    console.log('PASS: list, paging, filters, search, per-file logs, cancel/restart, paths, folders, create, mobile, Escape; no JS errors or network requests.');
  } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
